server {
    listen 80;
    root  /usr/share/nginx/html;
    index index.html;

    # Reverse Proxy — ส่ง /api/* ไปที่ backend container
    location /api/ {
        proxy_pass         http://backend:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # SPA fallback — ทุก path กลับมาที่ index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}